#ifndef INCLUDE_COMPOSE_HPP
#define INCLUDE_COMPOSE_HPP

#ifdef HORIZ_OPENMP
# define COMPOSE_HORIZ_OPENMP
#endif

#ifdef COLUMN_OPENMP
# define COMPOSE_COLUMN_OPENMP
#endif

#define COMPOSE_MIMIC_GPU
#if defined COMPOSE_MIMIC_GPU
# if defined COMPOSE_COLUMN_OPENMP
#  undef COMPOSE_COLUMN_OPENMP
# endif
#endif

#endif
